#!/bin/bash

echo "🔧 BidAlbania PM2 Management Commands"
echo "====================================="
echo ""
echo "📊 Status Commands:"
echo "  pm2 status                    - Show all processes status"
echo "  pm2 logs                      - Show all logs"
echo "  pm2 logs bidalbania-backend   - Show backend logs only"
echo "  pm2 logs bidalbania-frontend  - Show frontend logs only"
echo ""
echo "🔄 Control Commands:"
echo "  pm2 restart all               - Restart all applications"
echo "  pm2 restart bidalbania-backend    - Restart backend only"
echo "  pm2 restart bidalbania-frontend   - Restart frontend only"
echo ""
echo "⏹️  Stop Commands:"
echo "  pm2 stop all                  - Stop all applications"
echo "  pm2 stop bidalbania-backend       - Stop backend only"
echo "  pm2 stop bidalbania-frontend      - Stop frontend only"
echo ""
echo "🗑️  Delete Commands:"
echo "  pm2 delete all                - Delete all applications"
echo "  pm2 delete bidalbania-backend     - Delete backend only"
echo "  pm2 delete bidalbania-frontend    - Delete frontend only"
echo ""
echo "🚀 Start Commands:"
echo "  pm2 start ecosystem.config.js     - Start all applications"
echo "  pm2 start bidalbania-backend      - Start backend only"
echo "  pm2 start bidalbania-frontend     - Start frontend only"
echo ""
echo "💾 Save & Startup:"
echo "  pm2 save                      - Save current PM2 configuration"
echo "  pm2 startup                   - Generate startup script"
echo ""
echo "📈 Monitoring:"
echo "  pm2 monit                     - Open PM2 monitoring dashboard"
echo "  pm2 show bidalbania-backend       - Show detailed backend info"
echo "  pm2 show bidalbania-frontend      - Show detailed frontend info"
echo ""
echo "🌐 Application URLs:"
echo "  Frontend: http://your-server-ip:8000"
echo "  Backend:  http://your-server-ip:5000" 