const db = require('./config/database');
const bcrypt = require('bcryptjs');

console.log('Duke populluar databazën me të dhëna...');

// Sample users for requests
const sampleUsers = [
  { firstName: 'Ana', lastName: 'Gjoka', email: 'ana@example.com', phone: '+355 69 123 4567', city: 'Tiranë' },
  { firstName: 'Mark', lastName: 'Dedja', email: 'mark@example.com', phone: '+355 68 234 5678', city: 'Durrës' },
  { firstName: 'Elena', lastName: 'Hoxha', email: 'elena@example.com', phone: '+355 67 345 6789', city: 'Vlorë' },
  { firstName: 'Bardh', lastName: 'Kola', email: 'bardh@example.com', phone: '+355 66 456 7890', city: 'Shkodër' },
  { firstName: 'Mira', lastName: 'Leka', email: 'mira@example.com', phone: '+355 65 567 8901', city: 'Elbasan' },
  { firstName: 'Dritan', lastName: 'Mema', email: 'dritan@example.com', phone: '+355 64 678 9012', city: 'Fier' },
  { firstName: 'Arta', lastName: 'Ndoja', email: 'arta@example.com', phone: '+355 63 789 0123', city: 'Berat' },
  { firstName: 'Erion', lastName: 'Pali', email: 'erion@example.com', phone: '+355 62 890 1234', city: 'Korçë' }
];

// Sample requests for each category
const sampleRequests = [
  // Elektricist
  {
    title: 'Riparim instalimi elektrik në kuzhinë',
    description: 'Kam probleme me prizat në kuzhinë. Ndonjëherë nuk punojnë dhe ndonjëherë bëjnë shkëndija. Duhet një elektricist i përvojshëm për të kontrolluar dhe riparuar instalimin.',
    category: 'Elektricist',
    city: 'Tiranë',
    address: 'Rr. Myslym Shyri, Nr. 45, Pallati 3, Kati 2',
    postalCode: '1001',
    desiredDate: '2024-02-15',
    budget: '8000 Lekë',
    budgetType: 'fixed',
    urgency: 'high',
    propertyType: 'Apartament',
    propertySize: '80m²',
    contactPreference: 'phone',
    additionalRequirements: 'Preferoj që të jetë i verifikuar dhe me përvojë'
  },
  {
    title: 'Instalim kondicioneri në dhomën e gjumit',
    description: 'Dëshiroj të instaloj një kondicioner të ri në dhomën e gjumit. Dhoma është rreth 15m². Duhet instalim profesional dhe të sigurt.',
    category: 'Elektricist',
    city: 'Durrës',
    address: 'Rr. Sulejman Delvina, Nr. 12',
    postalCode: '2000',
    desiredDate: '2024-02-20',
    budget: '15000 Lekë',
    budgetType: 'negotiable',
    urgency: 'normal',
    propertyType: 'Apartament',
    propertySize: '65m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Kondicioneri do ta blej vetë, duhet vetëm instalim'
  },
  {
    title: 'Zëvendësim llambash LED në të gjithë shtëpinë',
    description: 'Dëshiroj të zëvendësoj të gjitha llambat e vjetra me LED moderne për të kursyer energji. Shtëpia ka 3 dhoma, kuzhinë, banjo dhe korridor.',
    category: 'Elektricist',
    city: 'Vlorë',
    address: 'Rr. Ismail Qemali, Nr. 78',
    postalCode: '9401',
    desiredDate: '2024-02-25',
    budget: '12000 Lekë',
    budgetType: 'fixed',
    urgency: 'low',
    propertyType: 'Shtëpi',
    propertySize: '120m²',
    contactPreference: 'email',
    additionalRequirements: 'Preferoj llamba LED të cilësisë së lartë'
  },
  {
    title: 'Riparim panel elektrik',
    description: 'Panel elektrik i shtëpisë ka probleme. Ndonjëherë bie rryma dhe duhet të resetoj siguresat. Duhet inspektim dhe riparim.',
    category: 'Elektricist',
    city: 'Shkodër',
    address: 'Rr. 28 Nëntori, Nr. 34',
    postalCode: '4001',
    desiredDate: '2024-02-18',
    budget: '10000 Lekë',
    budgetType: 'range',
    urgency: 'urgent',
    propertyType: 'Shtëpi',
    propertySize: '150m²',
    contactPreference: 'phone',
    additionalRequirements: 'Problemi është urgjent, duhet zgjidhje e shpejtë'
  },
  {
    title: 'Instalim sistem ndriçimi për oborr',
    description: 'Dëshiroj të instaloj ndriçim për oborrin e shtëpisë. Duhet sensorë lëvizjeje dhe llamba LED të fuqishme.',
    category: 'Elektricist',
    city: 'Elbasan',
    address: 'Rr. Qemal Stafa, Nr. 56',
    postalCode: '3001',
    desiredDate: '2024-03-01',
    budget: '18000 Lekë',
    budgetType: 'negotiable',
    urgency: 'normal',
    propertyType: 'Vila',
    propertySize: '200m²',
    contactPreference: 'any',
    additionalRequirements: 'Oborri është i madh, duhen disa llamba'
  },
  {
    title: 'Riparim priza në banjo',
    description: 'Prizat në banjo nuk punojnë mirë. Ndonjëherë bëjnë shkëndija dhe më frikësojnë. Duhet riparim i sigurt.',
    category: 'Elektricist',
    city: 'Fier',
    address: 'Rr. Gjergj Kastrioti, Nr. 23',
    postalCode: '9301',
    desiredDate: '2024-02-22',
    budget: '6000 Lekë',
    budgetType: 'fixed',
    urgency: 'high',
    propertyType: 'Apartament',
    propertySize: '70m²',
    contactPreference: 'phone',
    additionalRequirements: 'Problemi është i rrezikshëm, duhet riparim i menjëhershëm'
  },
  {
    title: 'Instalim sistem alarmi',
    description: 'Dëshiroj të instaloj sistem alarmi për shtëpinë. Duhet sensorë për dyer dhe dritare, plus panel kontrolli.',
    category: 'Elektricist',
    city: 'Berat',
    address: 'Rr. Antipatrea, Nr. 89',
    postalCode: '5001',
    desiredDate: '2024-02-28',
    budget: '25000 Lekë',
    budgetType: 'negotiable',
    urgency: 'normal',
    propertyType: 'Shtëpi',
    propertySize: '180m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Shtëpia ka 2 kate, duhet sistem i plotë'
  },
  {
    title: 'Riparim ngrohës uji',
    description: 'Ngrohësi i ujit nuk punon. Nuk ngroh ujin dhe bën zhurmë të çuditshme. Duhet diagnostikim dhe riparim.',
    category: 'Elektricist',
    city: 'Korçë',
    address: 'Rr. Fan Noli, Nr. 67',
    postalCode: '7001',
    desiredDate: '2024-02-19',
    budget: '8000 Lekë',
    budgetType: 'fixed',
    urgency: 'high',
    propertyType: 'Apartament',
    propertySize: '85m²',
    contactPreference: 'phone',
    additionalRequirements: 'Nëse nuk mund të riparohet, duhet zëvendësim'
  },

  // Hidraulik
  {
    title: 'Riparim rrjedhje në banjo',
    description: 'Ka rrjedhje në banjo. Uji rrjedh nga tubi i dushit dhe po dëmton dyshemenë. Duhet riparim i menjëhershëm.',
    category: 'Hidraulik',
    city: 'Tiranë',
    address: 'Rr. Dëshmorët e Kombit, Nr. 123',
    postalCode: '1001',
    desiredDate: '2024-02-16',
    budget: '7000 Lekë',
    budgetType: 'fixed',
    urgency: 'urgent',
    propertyType: 'Apartament',
    propertySize: '75m²',
    contactPreference: 'phone',
    additionalRequirements: 'Problemi është urgjent, uji po dëmton dyshemenë'
  },
  {
    title: 'Instalim lavaman i ri në kuzhinë',
    description: 'Dëshiroj të zëvendësoj lavamanin e vjetër në kuzhinë me një të ri, modern. Duhet instalim profesional.',
    category: 'Hidraulik',
    city: 'Durrës',
    address: 'Rr. Adria, Nr. 45',
    postalCode: '2000',
    desiredDate: '2024-02-23',
    budget: '15000 Lekë',
    budgetType: 'negotiable',
    urgency: 'normal',
    propertyType: 'Apartament',
    propertySize: '90m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Lavamani do ta blej vetë, duhet vetëm instalim'
  },
  {
    title: 'Riparim sistem ngrohje',
    description: 'Sistemi i ngrohjes nuk punon mirë. Radiatorët nuk ngrohen dhe ka probleme me pompën. Duhet diagnostikim.',
    category: 'Hidraulik',
    city: 'Vlorë',
    address: 'Rr. Vangjel Pandeli, Nr. 78',
    postalCode: '9401',
    desiredDate: '2024-02-26',
    budget: '20000 Lekë',
    budgetType: 'range',
    urgency: 'high',
    propertyType: 'Shtëpi',
    propertySize: '140m²',
    contactPreference: 'phone',
    additionalRequirements: 'Sistemi është i vjetër, mund të duhet zëvendësim'
  },
  {
    title: 'Instalim WC i ri',
    description: 'Dëshiroj të instaloj një WC të ri në banjon e ri. Duhet instalim i plotë me tuba të rinj.',
    category: 'Hidraulik',
    city: 'Shkodër',
    address: 'Rr. 13 Dhjetori, Nr. 12',
    postalCode: '4001',
    desiredDate: '2024-02-24',
    budget: '12000 Lekë',
    budgetType: 'fixed',
    urgency: 'normal',
    propertyType: 'Apartament',
    propertySize: '80m²',
    contactPreference: 'email',
    additionalRequirements: 'WC-në do ta blej vetë, duhet instalim profesional'
  },
  {
    title: 'Riparim tuba uji në oborr',
    description: 'Tubat e ujit në oborr kanë rrjedhje. Uji po humbet dhe po rrit faturën. Duhet riparim i shpejtë.',
    category: 'Hidraulik',
    city: 'Elbasan',
    address: 'Rr. 5 Maji, Nr. 34',
    postalCode: '3001',
    desiredDate: '2024-02-20',
    budget: '10000 Lekë',
    budgetType: 'fixed',
    urgency: 'high',
    propertyType: 'Shtëpi',
    propertySize: '160m²',
    contactPreference: 'phone',
    additionalRequirements: 'Problemi është i shtrenjtë, duhet zgjidhje e shpejtë'
  },
  {
    title: 'Instalim sistem uji i butë',
    description: 'Dëshiroj të instaloj sistem uji i butë për të gjithë shtëpinë. Uji i qytetit është shumë i fortë.',
    category: 'Hidraulik',
    city: 'Fier',
    address: 'Rr. 1 Maji, Nr. 67',
    postalCode: '9301',
    desiredDate: '2024-03-05',
    budget: '35000 Lekë',
    budgetType: 'negotiable',
    urgency: 'low',
    propertyType: 'Vila',
    propertySize: '220m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Duhet sistem i cilësisë së lartë për shtëpi të madhe'
  },
  {
    title: 'Riparim dush në banjo',
    description: 'Dushi në banjo nuk punon mirë. Presioni i ujit është i ulët dhe temperatura nuk rregullohet.',
    category: 'Hidraulik',
    city: 'Berat',
    address: 'Rr. Republika, Nr. 89',
    postalCode: '5001',
    desiredDate: '2024-02-21',
    budget: '8000 Lekë',
    budgetType: 'fixed',
    urgency: 'normal',
    propertyType: 'Apartament',
    propertySize: '70m²',
    contactPreference: 'phone',
    additionalRequirements: 'Mund të duhet zëvendësim i plotë i dushit'
  },
  {
    title: 'Instalim sistem uji për kopsht',
    description: 'Dëshiroj të instaloj sistem uji për kopshtin. Duhen sprinklerë dhe tuba për ujitje automatike.',
    category: 'Hidraulik',
    city: 'Korçë',
    address: 'Rr. Kristaq Tutulani, Nr. 45',
    postalCode: '7001',
    desiredDate: '2024-03-10',
    budget: '28000 Lekë',
    budgetType: 'negotiable',
    urgency: 'low',
    propertyType: 'Vila',
    propertySize: '300m²',
    contactPreference: 'email',
    additionalRequirements: 'Kopshti është i madh, duhet sistem i plotë'
  },

  // Pastrim
  {
    title: 'Pastrim i plotë shtëpie pas renovimit',
    description: 'Sapo përfundova renovimin e shtëpisë dhe duhet pastrim i plotë. Ka pluhur dhe mbeturina kudo.',
    category: 'Pastrim',
    city: 'Tiranë',
    address: 'Rr. Myslym Shyri, Nr. 78',
    postalCode: '1001',
    desiredDate: '2024-02-17',
    budget: '12000 Lekë',
    budgetType: 'fixed',
    urgency: 'high',
    propertyType: 'Apartament',
    propertySize: '95m²',
    contactPreference: 'phone',
    additionalRequirements: 'Duhet pastrim i thellë dhe profesional'
  },
  {
    title: 'Pastrim dritaresh në zyrë',
    description: 'Dëshiroj pastrim dritaresh për zyrën. Ka 15 dritare që duhen pastruar nga jashtë dhe brenda.',
    category: 'Pastrim',
    city: 'Durrës',
    address: 'Rr. Sulejman Delvina, Nr. 34',
    postalCode: '2000',
    desiredDate: '2024-02-25',
    budget: '8000 Lekë',
    budgetType: 'fixed',
    urgency: 'normal',
    propertyType: 'Zyra',
    propertySize: '200m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Dritaret janë të larta, duhet pajisje speciale'
  },
  {
    title: 'Pastrim tapiserie dhe divane',
    description: 'Dëshiroj pastrim tapiserie për divanet dhe karriget në shtëpi. Ka njolla dhe pluhur që duhen hequr.',
    category: 'Pastrim',
    city: 'Vlorë',
    address: 'Rr. Ismail Qemali, Nr. 56',
    postalCode: '9401',
    desiredDate: '2024-02-28',
    budget: '15000 Lekë',
    budgetType: 'negotiable',
    urgency: 'low',
    propertyType: 'Apartament',
    propertySize: '110m²',
    contactPreference: 'email',
    additionalRequirements: 'Tapiseri është e ndjeshme, duhet kujdes i veçantë'
  },
  {
    title: 'Pastrim i përditshëm për restorant',
    description: 'Dëshiroj shërbim pastrimi të përditshëm për restorantin. Duhet pastrim kuzhine, tavolina dhe banjo.',
    category: 'Pastrim',
    city: 'Shkodër',
    address: 'Rr. 28 Nëntori, Nr. 90',
    postalCode: '4001',
    desiredDate: '2024-02-26',
    budget: '25000 Lekë',
    budgetType: 'negotiable',
    urgency: 'high',
    propertyType: 'Restorant',
    propertySize: '150m²',
    contactPreference: 'phone',
    additionalRequirements: 'Duhet pastrim i përditshëm, kontratë afatgjatë'
  },
  {
    title: 'Pastrim kuzhine pas gatuar',
    description: 'Kuzhina është shumë e ndyrë pas gatuar për një event. Duhet pastrim i thellë dhe i shpejtë.',
    category: 'Pastrim',
    city: 'Elbasan',
    address: 'Rr. Qemal Stafa, Nr. 23',
    postalCode: '3001',
    desiredDate: '2024-02-18',
    budget: '6000 Lekë',
    budgetType: 'fixed',
    urgency: 'urgent',
    propertyType: 'Shtëpi',
    propertySize: '130m²',
    contactPreference: 'phone',
    additionalRequirements: 'Duhet pastrim i menjëhershëm, eventi është sot'
  },
  {
    title: 'Pastrim hotel pas eventi',
    description: 'Dëshiroj pastrim të plotë për hotelin pas një eventi të madh. Duhet pastrim dhoma, korridore dhe hapësira të përgjithshme.',
    category: 'Pastrim',
    city: 'Fier',
    address: 'Rr. Gjergj Kastrioti, Nr. 45',
    postalCode: '9301',
    desiredDate: '2024-02-27',
    budget: '50000 Lekë',
    budgetType: 'negotiable',
    urgency: 'high',
    propertyType: 'Hotel',
    propertySize: '500m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Duhet ekip i madh dhe pastrim i plotë'
  },
  {
    title: 'Pastrim dyshemeje dhe qilimash',
    description: 'Dëshiroj pastrim dyshemeje dhe qilimash në shtëpi. Dyshemetë janë prej parketi dhe ka qilima që duhen pastruar.',
    category: 'Pastrim',
    city: 'Berat',
    address: 'Rr. Antipatrea, Nr. 67',
    postalCode: '5001',
    desiredDate: '2024-02-29',
    budget: '18000 Lekë',
    budgetType: 'fixed',
    urgency: 'normal',
    propertyType: 'Shtëpi',
    propertySize: '160m²',
    contactPreference: 'email',
    additionalRequirements: 'Parketi është i ndjeshëm, duhet kujdes i veçantë'
  },
  {
    title: 'Pastrim zyre pas zhvendosje',
    description: 'Zvenda u zhvendos në zyrë të re dhe duhet pastrim i plotë. Ka kuti, letra dhe mbeturina kudo.',
    category: 'Pastrim',
    city: 'Korçë',
    address: 'Rr. Fan Noli, Nr. 34',
    postalCode: '7001',
    desiredDate: '2024-02-22',
    budget: '10000 Lekë',
    budgetType: 'fixed',
    urgency: 'high',
    propertyType: 'Zyra',
    propertySize: '120m²',
    contactPreference: 'phone',
    additionalRequirements: 'Duhet pastrim i shpejtë, zyra duhet të jetë gati për punë'
  },

  // Pikturë & Lyerje
  {
    title: 'Lyerje e plotë shtëpie',
    description: 'Dëshiroj lyerje të plotë të shtëpisë. Të gjitha dhomat dhe korridoret duhen lyer me ngjyra moderne.',
    category: 'Pikturë',
    city: 'Tiranë',
    address: 'Rr. Dëshmorët e Kombit, Nr. 234',
    postalCode: '1001',
    desiredDate: '2024-03-01',
    budget: '45000 Lekë',
    budgetType: 'negotiable',
    urgency: 'normal',
    propertyType: 'Shtëpi',
    propertySize: '180m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Preferoj ngjyra të qeta dhe moderne'
  },
  {
    title: 'Lyerje fasadë shtëpie',
    description: 'Fasada e shtëpisë është e vjetër dhe duhet lyerje e re. Duhet ngjyrë e qëndrueshme për motin.',
    category: 'Pikturë',
    city: 'Durrës',
    address: 'Rr. Adria, Nr. 78',
    postalCode: '2000',
    desiredDate: '2024-03-05',
    budget: '35000 Lekë',
    budgetType: 'fixed',
    urgency: 'low',
    propertyType: 'Shtëpi',
    propertySize: '200m²',
    contactPreference: 'phone',
    additionalRequirements: 'Duhet ngjyrë e qëndrueshme për motin e keq'
  },
  {
    title: 'Lyerje dhomë gjumi',
    description: 'Dëshiroj të lyer dhomën e gjumit me një ngjyrë të re. Preferoj ngjyra të qeta dhe relaksuese.',
    category: 'Pikturë',
    city: 'Vlorë',
    address: 'Rr. Vangjel Pandeli, Nr. 45',
    postalCode: '9401',
    desiredDate: '2024-02-25',
    budget: '12000 Lekë',
    budgetType: 'fixed',
    urgency: 'normal',
    propertyType: 'Apartament',
    propertySize: '85m²',
    contactPreference: 'email',
    additionalRequirements: 'Ngjyrën do ta zgjedh bashkë me lyerësin'
  },
  {
    title: 'Lyerje kuzhine',
    description: 'Kuzhina duhet lyerje e re. Duhet ngjyrë e qëndrueshme për nxehtësi dhe lagështi.',
    category: 'Pikturë',
    city: 'Shkodër',
    address: 'Rr. 13 Dhjetori, Nr. 67',
    postalCode: '4001',
    desiredDate: '2024-02-28',
    budget: '15000 Lekë',
    budgetType: 'negotiable',
    urgency: 'normal',
    propertyType: 'Apartament',
    propertySize: '90m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Duhet ngjyrë e qëndrueshme për kuzhinë'
  },
  {
    title: 'Lyerje banjo',
    description: 'Banjo duhet lyerje e re. Duhet ngjyrë e qëndrueshme për lagështi dhe pastrim të lehtë.',
    category: 'Pikturë',
    city: 'Elbasan',
    address: 'Rr. 5 Maji, Nr. 89',
    postalCode: '3001',
    desiredDate: '2024-03-02',
    budget: '10000 Lekë',
    budgetType: 'fixed',
    urgency: 'low',
    propertyType: 'Apartament',
    propertySize: '75m²',
    contactPreference: 'phone',
    additionalRequirements: 'Duhet ngjyrë e qëndrueshme për banjo'
  },
  {
    title: 'Dekorim dhomë djesh',
    description: 'Dëshiroj dekorim special për dhomën e djeshit. Duhet ngjyra të bukura dhe dizajn modern.',
    category: 'Pikturë',
    city: 'Fier',
    address: 'Rr. 1 Maji, Nr. 123',
    postalCode: '9301',
    desiredDate: '2024-03-08',
    budget: '25000 Lekë',
    budgetType: 'negotiable',
    urgency: 'low',
    propertyType: 'Shtëpi',
    propertySize: '140m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Duhet dizajn modern dhe ngjyra të bukura'
  },
  {
    title: 'Lyerje zyre',
    description: 'Zvenda duhet lyerje e re. Duhet ngjyrë profesionale dhe moderne për ambiente pune.',
    category: 'Pikturë',
    city: 'Berat',
    address: 'Rr. Republika, Nr. 45',
    postalCode: '5001',
    desiredDate: '2024-02-26',
    budget: '20000 Lekë',
    budgetType: 'fixed',
    urgency: 'normal',
    propertyType: 'Zyra',
    propertySize: '100m²',
    contactPreference: 'email',
    additionalRequirements: 'Duhet ngjyrë profesionale për zyrë'
  },
  {
    title: 'Lyerje gardhe',
    description: 'Gardhi i oborrit duhet lyerje e re. Duhet ngjyrë e qëndrueshme për motin e jashtëm.',
    category: 'Pikturë',
    city: 'Korçë',
    address: 'Rr. Kristaq Tutulani, Nr. 78',
    postalCode: '7001',
    desiredDate: '2024-03-10',
    budget: '18000 Lekë',
    budgetType: 'negotiable',
    urgency: 'low',
    propertyType: 'Vila',
    propertySize: '250m²',
    contactPreference: 'phone',
    additionalRequirements: 'Duhet ngjyrë e qëndrueshme për motin'
  },

  // Mobilieri
  {
    title: 'Instalim mobilieri kuzhine',
    description: 'Dëshiroj instalim mobilieri të re për kuzhinë. Kam blerë mobilieri moderne dhe duhet instalim profesional.',
    category: 'Mobilieri',
    city: 'Tiranë',
    address: 'Rr. Myslym Shyri, Nr. 156',
    postalCode: '1001',
    desiredDate: '2024-02-20',
    budget: '30000 Lekë',
    budgetType: 'fixed',
    urgency: 'normal',
    propertyType: 'Apartament',
    propertySize: '95m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Mobilieri është e shtrenjtë, duhet instalim i kujdesshëm'
  },
  {
    title: 'Riparim tavolina në kuzhinë',
    description: 'Tavolina në kuzhinë ka probleme. Një këmbë është e lirë dhe duhet riparim. Është tavolinë e vjetër por e bukur.',
    category: 'Mobilieri',
    city: 'Durrës',
    address: 'Rr. Sulejman Delvina, Nr. 90',
    postalCode: '2000',
    desiredDate: '2024-02-22',
    budget: '5000 Lekë',
    budgetType: 'fixed',
    urgency: 'normal',
    propertyType: 'Apartament',
    propertySize: '80m²',
    contactPreference: 'phone',
    additionalRequirements: 'Tavolina është e vjetër por e vlefshme, duhet riparim i kujdesshëm'
  },
  {
    title: 'Instalim garderobë në dhomë gjumi',
    description: 'Dëshiroj instalim garderobë të re në dhomën e gjumit. Duhet garderobë e madhe me shumë hapësirë.',
    category: 'Mobilieri',
    city: 'Vlorë',
    address: 'Rr. Ismail Qemali, Nr. 34',
    postalCode: '9401',
    desiredDate: '2024-02-27',
    budget: '25000 Lekë',
    budgetType: 'negotiable',
    urgency: 'low',
    propertyType: 'Apartament',
    propertySize: '100m²',
    contactPreference: 'email',
    additionalRequirements: 'Duhet garderobë e madhe me shumë rafte dhe tërheqëse'
  },
  {
    title: 'Riparim karrige në zyrë',
    description: 'Karriget në zyrë kanë probleme. Disa janë të lira dhe duhen riparuar. Janë karrige të shtrenjta.',
    category: 'Mobilieri',
    city: 'Shkodër',
    address: 'Rr. 28 Nëntori, Nr. 78',
    postalCode: '4001',
    desiredDate: '2024-02-24',
    budget: '8000 Lekë',
    budgetType: 'fixed',
    urgency: 'normal',
    propertyType: 'Zyra',
    propertySize: '120m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Karriget janë të shtrenjta, duhet riparim i kujdesshëm'
  },
  {
    title: 'Instalim rafte librash',
    description: 'Dëshiroj instalim rafte librash në dhomën e djeshit. Duhen rafte të mëdha për librat e mi.',
    category: 'Mobilieri',
    city: 'Elbasan',
    address: 'Rr. Qemal Stafa, Nr. 45',
    postalCode: '3001',
    desiredDate: '2024-03-01',
    budget: '15000 Lekë',
    budgetType: 'negotiable',
    urgency: 'low',
    propertyType: 'Shtëpi',
    propertySize: '150m²',
    contactPreference: 'phone',
    additionalRequirements: 'Duhen rafte të mëdha dhe të forta për librat'
  },
  {
    title: 'Riparim komodë në dhomë gjumi',
    description: 'Komoda në dhomën e gjumit ka probleme me tërheqëset. Disa nuk hapen dhe duhen riparuar.',
    category: 'Mobilieri',
    city: 'Fier',
    address: 'Rr. Gjergj Kastrioti, Nr. 67',
    postalCode: '9301',
    desiredDate: '2024-02-26',
    budget: '6000 Lekë',
    budgetType: 'fixed',
    urgency: 'normal',
    propertyType: 'Apartament',
    propertySize: '85m²',
    contactPreference: 'email',
    additionalRequirements: 'Komoda është e bukur, duhet riparim i kujdesshëm'
  },
  {
    title: 'Instalim tavolina në zyrë',
    description: 'Dëshiroj instalim tavolina të re për zyrën. Duhet tavolinë e madhe për takime dhe punë.',
    category: 'Mobilieri',
    city: 'Berat',
    address: 'Rr. Antipatrea, Nr. 23',
    postalCode: '5001',
    desiredDate: '2024-02-29',
    budget: '20000 Lekë',
    budgetType: 'negotiable',
    urgency: 'normal',
    propertyType: 'Zyra',
    propertySize: '80m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Duhet tavolinë e madhe dhe profesionale'
  },
  {
    title: 'Riparim dollap në banjo',
    description: 'Dollapi në banjo ka probleme me dyer. Një derë nuk mbyllet mirë dhe duhet riparim.',
    category: 'Mobilieri',
    city: 'Korçë',
    address: 'Rr. Fan Noli, Nr. 56',
    postalCode: '7001',
    desiredDate: '2024-02-25',
    budget: '4000 Lekë',
    budgetType: 'fixed',
    urgency: 'normal',
    propertyType: 'Apartament',
    propertySize: '90m²',
    contactPreference: 'phone',
    additionalRequirements: 'Dollapi është i ri, duhet riparim i kujdesshëm'
  },

  // Kopshtari
  {
    title: 'Kujdesje oborr dhe kopsht',
    description: 'Dëshiroj kujdesje të përditshme për oborrin dhe kopshtin. Duhet prerje bar, ujitje dhe kujdesje për pemët.',
    category: 'Kopshtari',
    city: 'Tiranë',
    address: 'Rr. Dëshmorët e Kombit, Nr. 345',
    postalCode: '1001',
    desiredDate: '2024-02-18',
    budget: '20000 Lekë',
    budgetType: 'negotiable',
    urgency: 'normal',
    propertyType: 'Vila',
    propertySize: '300m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Duhet kujdesje të përditshme, kontratë afatgjatë'
  },
  {
    title: 'Prerje pemë në oborr',
    description: 'Pemët në oborr janë shumë të mëdha dhe duhen prerë. Disa degë janë të rrezikshme dhe duhen hequr.',
    category: 'Kopshtari',
    city: 'Durrës',
    address: 'Rr. Adria, Nr. 123',
    postalCode: '2000',
    desiredDate: '2024-02-21',
    budget: '15000 Lekë',
    budgetType: 'fixed',
    urgency: 'high',
    propertyType: 'Shtëpi',
    propertySize: '250m²',
    contactPreference: 'phone',
    additionalRequirements: 'Pemët janë të mëdha dhe të rrezikshme, duhet specialist'
  },
  {
    title: 'Instalim sistem ujitje automatike',
    description: 'Dëshiroj instalim sistem ujitje automatike për kopshtin. Duhet sprinklerë dhe kontroll automatik.',
    category: 'Kopshtari',
    city: 'Vlorë',
    address: 'Rr. Vangjel Pandeli, Nr. 89',
    postalCode: '9401',
    desiredDate: '2024-03-05',
    budget: '30000 Lekë',
    budgetType: 'negotiable',
    urgency: 'low',
    propertyType: 'Vila',
    propertySize: '400m²',
    contactPreference: 'email',
    additionalRequirements: 'Kopshti është i madh, duhet sistem i plotë'
  },
  {
    title: 'Pranjë lulesh në oborr',
    description: 'Dëshiroj pranjë lulesh të bukura në oborr. Duhet lule të cilësisë së lartë dhe dizajn të bukur.',
    category: 'Kopshtari',
    city: 'Shkodër',
    address: 'Rr. 13 Dhjetori, Nr. 45',
    postalCode: '4001',
    desiredDate: '2024-02-28',
    budget: '25000 Lekë',
    budgetType: 'negotiable',
    urgency: 'low',
    propertyType: 'Shtëpi',
    propertySize: '200m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Duhet lule të bukura dhe dizajn modern'
  },
  {
    title: 'Kujdesje pemë frutash',
    description: 'Pemët frutash në oborr duhen kujdesje speciale. Duhet prerje, plehërim dhe mbrojtje nga sëmundjet.',
    category: 'Kopshtari',
    city: 'Elbasan',
    address: 'Rr. 5 Maji, Nr. 67',
    postalCode: '3001',
    desiredDate: '2024-02-25',
    budget: '18000 Lekë',
    budgetType: 'fixed',
    urgency: 'normal',
    propertyType: 'Shtëpi',
    propertySize: '180m²',
    contactPreference: 'phone',
    additionalRequirements: 'Duhet specialist për pemë frutash'
  },
  {
    title: 'Instalim gardhe bimësh',
    description: 'Dëshiroj instalim gardhe bimësh për të mbrojtur kopshtin. Duhet gardhe e bukur dhe e qëndrueshme.',
    category: 'Kopshtari',
    city: 'Fier',
    address: 'Rr. 1 Maji, Nr. 90',
    postalCode: '9301',
    desiredDate: '2024-03-01',
    budget: '22000 Lekë',
    budgetType: 'negotiable',
    urgency: 'low',
    propertyType: 'Vila',
    propertySize: '350m²',
    contactPreference: 'email',
    additionalRequirements: 'Duhet gardhe e bukur dhe e qëndrueshme'
  },
  {
    title: 'Kujdesje lule në shtëpi',
    description: 'Dëshiroj kujdesje për lulet në shtëpi. Duhet ujitje, plehërim dhe kujdesje speciale për lulet e brendshme.',
    category: 'Kopshtari',
    city: 'Berat',
    address: 'Rr. Republika, Nr. 78',
    postalCode: '5001',
    desiredDate: '2024-02-27',
    budget: '8000 Lekë',
    budgetType: 'fixed',
    urgency: 'normal',
    propertyType: 'Apartament',
    propertySize: '100m²',
    contactPreference: 'whatsapp',
    additionalRequirements: 'Lulet janë të shtrenjta, duhet kujdesje e veçantë'
  },
  {
    title: 'Pranjë pemë dekorative',
    description: 'Dëshiroj pranjë pemë dekorative në oborr. Duhet pemë të bukura që të rriten mirë në klimën tonë.',
    category: 'Kopshtari',
    city: 'Korçë',
    address: 'Rr. Kristaq Tutulani, Nr. 34',
    postalCode: '7001',
    desiredDate: '2024-03-08',
    budget: '35000 Lekë',
    budgetType: 'negotiable',
    urgency: 'low',
    propertyType: 'Vila',
    propertySize: '280m²',
    contactPreference: 'phone',
    additionalRequirements: 'Duhet pemë të bukura që të rriten mirë në klimën tonë'
  }
]